export const ROUTES = {
  CONGRATULATION: '/auth/congratulation',
  CREATE: '/create',
  CREATE_NEW_PASSWORD: '/auth/create-new-password',
  DEFAULT: '/',
  FAVORITES: '/favorites',
  FORGOT_PASS: '/auth/forgot-password',
  HOME: '/home',
  LOGIN: '/auth/sign-in',
  MESSENGER: '/messenger',
  PROFILE: '/profile',
  REGISTER: '/auth/sign-up',
  SEARCH: '/search',
  STATISTICS: '/statistics',
  VERIFICATION_LINK_EXPIRED: '/auth/forgot-password/verification-link-expired',
}
export const PRIVATE_ROUTES = [
  ROUTES.DEFAULT,
  ROUTES.HOME,
  ROUTES.CREATE,
  ROUTES.PROFILE,
  ROUTES.SEARCH,
  ROUTES.STATISTICS,
  ROUTES.FAVORITES,
  ROUTES.MESSENGER,
]
